version: '3.8'

services:
 mysqldb:
  image: mysql
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=init_pwd
  volumes:
   - mysql:/var/lib/mysql
   - mysql_config:/etc/mysql
  networks:
   - fake_net

 fake_news:
  build:
   context: .
  command: >
   sh -c "python3 db_setup.py &&
          pytest -v > test.log &&
          uvicorn main:app --host 0.0.0.0 --port 8000"
  ports:
  - 8000:8000
  volumes:
  - ./:/app
  networks:
   - fake_net
  depends_on:
   - mysqldb

volumes:
  mysql:
  mysql_config:

networks:
 fake_net:
  driver: bridge
